config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'profile', to: 'dashboard#profile'
  root to: 'pages#home'
  patch 'procedures/:id/accept', to: 'procedures#accept', as: "accept"
  patch 'procedures/:id/refuse', to: 'procedures#refuse', as: "refuse"
  get 'procedures/:id/payment', to: 'procedures#payment', as: "payment"

  resources :users, only: [:edit, :update]
  resources :services do
    resources :procedures, except: [:destroy]
  end

  # get '/edit_lawyer', to: 'users#edit_lawyer', as: 'edit_lawyer'

  get '/service_divorce', to: 'services#divorce', as: 'service_divorce'

  get '/profile_saul', to: 'services#profile_saul', as: 'profile_saul'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/procedure.rb
class Procedure < ApplicationRecord
  belongs_to :user
  belongs_to :service

  validates :date, :grievance, presence: true
end

app/models/service.rb
class Service < ApplicationRecord
  CATEGORIES = ["Divorce", "Pension Alimentaire", "Stationnement", "Excès de vitesse", "Licenciement", "Harcèlement", "Fiscalité", "Impayés", "Abus de faiblesse", "Traffic d'influence", "Corruption", "Financement illégal"]
  belongs_to :user
  has_many :procedures, dependent: :destroy
  validates :title, presence: true
  validates :description, presence: true
  validates :duration, presence: true
  validates :price, presence: true
  validates :category, presence: true, inclusion: { in: CATEGORIES }

  include PgSearch::Model
  pg_search_scope :global_search,
    against: [:category, :title, :description],
    associated_against: {
      user: [:last_name, :first_name, :job, :address, :specialty]
    },
    using: {
      tsearch: { prefix: true }
    }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # validates :first_name, presence: true
  # validates :last_name, presence: true
  # validates :avatar, presence: true
  mount_uploader :avatar, PhotoUploader
  # verifier que cette ligne pour l'avatar est utile
  # has_attachment :avatar

  JOBS = ['Avocat', 'Notaire', 'Huissier', 'Juriste']
  # validates :job, inclusion: { in: JOBS }

  # has_many :proposed_services, through: :procedures, source: :services
  has_many :services, dependent: :destroy
  has_many :procedures, dependent: :destroy
  has_many :proposed_services, through: :services, source: :procedures

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def profile
    @user = current_user
    @jobs = @user.job
    @services = @user.services
    @procedures = @user.procedures
    @proposed_services = @user.proposed_services
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/procedures_controller.rb
class ProceduresController < ApplicationController
  before_action :current_procedure, only: [:show, :edit, :update, :payment]
  def index
    @procedures = Procedure.all
  end

  def show
  end

  def new
    @service = Service.find(params[:service_id])
    @procedure = Procedure.new
  end

  def create
    @service = Service.find(params[:service_id])
    @procedure = Procedure.new(procedure_params)
    @procedure.service = @service
    @procedure.user = current_user
    if @procedure.save
      # redirect_to service_path(@service), notice: 'Votre prestation a bien été créé.'
      redirect_to payment_path(@procedure), notice: 'Votre prestation a bien été créé.'
    else
      render 'new'
    end
  end

  def accept
    @procedure = Procedure.find(params[:id])
    @procedure.status = "accepted"
    @procedure.save
    redirect_to profile_path, notice: "Vous venez d'accepter une procédure."
  end

  def refuse
    @procedure = Procedure.find(params[:id])
    @procedure.status = "refused"
    @procedure.save
    redirect_to profile_path, notice: "Vous venez de refuser une procédure."
  end

  def payment
  end

  private

  def current_procedure
    @procedure = Procedure.find(params[:id])
  end

  def procedure_params
    params.require(:procedure).permit(:date, :grievance)
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:show, :edit, :update, :destroy]

  def index
    if params[:query].present?
      @services = Service.global_search(params[:query])
    else
      @services = Service.all
    end
  end

  def divorce
    @services = Service.all
  end

  def show
  end

  def profile_saul
  end

  def new
    @service = Service.new
  end

  def create
    @service = Service.new(service_params)
    @service.user = current_user
    if @service.save
      redirect_to profile_path, notice: 'Votre prestation a bien été créé.'
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @service.update(service_params)
      redirect_to profile_path, notice: 'Votre prestation a bien été modifié.'
    else
      render 'edit'
    end
  end

  def destroy
    @service.destroy
    redirect_to services_path, notice: 'Votre prestation a bien été supprimé.'
  end

  private

  def set_service
    @service = Service.find(params[:id])
  end

  def service_params
    params.require(:service).permit(:title, :description, :duration, :category, :price)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :edit_user, :update_lawyer]

  def dashboard
    # ajouter procedures et services liees à l'user id
  end

  def show
  end

  def edit
    render 'devise/registrations/edit'
  end

  # def edit_lawyer
  # end

  def update_lawyer
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render :edit_user
    end
  end

  def update
    if @user.update(user_params)
      redirect_to profile_path
    else
      render :edit
    end
  end

  def delete
    @user.destroy
    redirect_to destroy_user_session_path
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :job, :specialty, :experience, :description, :address, :avatar, :firm)
  end

  def set_user
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/profile.html.erb
<center><h2 class="m-4">Mes Procédures</h2></center>
<div class="container">
	<div class="row">

		<div class="procedures-subblock col-md-7">
		  <% if @jobs.present? %>
        <div class="card">
  				<div class="card-header text-center"><h4>Liste des procédures</h4>
          </div>
  				<div class="card-body">
            <div class="card-header padding-zero">En attente</div>
              <% @proposed_services.each do |procedure| %>
                <% if procedure.status == "pending" %>
  						    <ul class="list-group list-group-flush">
                    <li class="list-group-item list-procedure"><%= procedure.service.title %> | <%= procedure.date %>
                      <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#ProcedureModal<%= procedure.id %>">Détails</button>
                        <div class="modal fade" id="ProcedureModal<%= procedure.id %>" tabindex="-1" role="dialog" aria-labelledby="ProcedureModal-<%= procedure.id %>" aria-hidden="true">
                          <div class="modal-dialog modal-dialog-centered" role="document">
                            <div class="modal-content">
                              <div class="modal-header">
                                <h5 class="modal-title" id="ProcedureModal-<%= procedure.id %>"><%= procedure.service.title %></h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                  <span aria-hidden="true">&times;</span>
                                </button>
                              </div>
                              <div class="modal-body">
                                <%= simple_format procedure.grievance %>
                              </div>
                              <div class="modal-footer">
                                <%= link_to "Refuser", refuse_path(procedure), method: :patch, class: "btn btn-outline-danger" %>
                                <%= link_to "Accepter", accept_path(procedure), method: :patch, class: "btn btn-outline-success" %>
                              </div>
                            </div>
                          </div>
                        </div>
                    </li>
                  </ul>
                <% end %>
              <% end %>

            <div class="card-header padding-zero">En cours</div>
                <% @proposed_services.each do |procedure| %>
                  <% if procedure.status == "accepted" %>
      						  <ul class="list-group list-group-flush">
                      <li class="list-group-item list-procedure"><%= procedure.service.title %> | <%= procedure.date %>
                      <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#ProcedureModal<%= procedure.id %>">Détails</button>
                        <div class="modal fade" id="ProcedureModal<%= procedure.id %>" tabindex="-1" role="dialog" aria-labelledby="ProcedureModal-<%= procedure.id %>" aria-hidden="true">
                          <div class="modal-dialog modal-dialog-centered" role="document">
                            <div class="modal-content">
                              <div class="modal-header">
                                <h5 class="modal-title" id="ProcedureModal-<%= procedure.id %>"><%= procedure.service.title %></h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                  <span aria-hidden="true">&times;</span>
                                </button>
                              </div>
                              <div class="modal-body">
                                <%= simple_format procedure.grievance %>
                              </div>
                              <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Fermer</button>
                              </div>
                            </div>
                          </div>
                        </div>
                      </li>
                    </ul>
                  <% end %>
  					    <% end %>
  				    </div>
         <% else %>
         <div class="card">
          <div class="card-header text-center"><h4>Liste des procédures</h4>
          </div>
          <div class="card-body">
            <div class="card-header padding-zero">En attente</div>
              <% @procedures.each do |procedure| %>
                <% if procedure.status == "pending" %>
                  <ul class="list-group list-group-flush">
                    <li class="list-group-item list-procedure"><%= procedure.service.title %> | <%= procedure.date %>
                      <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#ProcedureModal<%= procedure.id %>">Détails</button>
                        <div class="modal fade" id="ProcedureModal<%= procedure.id %>" tabindex="-1" role="dialog" aria-labelledby="ProcedureModal-<%= procedure.id %>" aria-hidden="true">
                          <div class="modal-dialog modal-dialog-centered" role="document">
                            <div class="modal-content">
                              <div class="modal-header">
                                <h5 class="modal-title" id="ProcedureModal-<%= procedure.id %>"><%= procedure.service.title %></h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                  <span aria-hidden="true">&times;</span>
                                </button>
                              </div>
                              <div class="modal-body">
                                <%= simple_format procedure.grievance %>
                              </div>
                              <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Fermer
                                </button>
                              </div>
                            </div>
                          </div>
                        </div>
                    </li>
                  </ul>
                <% end %>
              <% end %>

            <div class="card-header padding-zero">En cours</div>
                <% @procedures.each do |procedure| %>
                  <% if procedure.status == "accepted" %>
                    <ul class="list-group list-group-flush">
                      <li class="list-group-item list-procedure"><%= procedure.service.title %> | <%= procedure.date %>
                      <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#ProcedureModal<%= procedure.id %>">Détails</button>
                        <div class="modal fade" id="ProcedureModal<%= procedure.id %>" tabindex="-1" role="dialog" aria-labelledby="ProcedureModal-<%= procedure.id %>" aria-hidden="true">
                          <div class="modal-dialog modal-dialog-centered" role="document">
                            <div class="modal-content">
                              <div class="modal-header">
                                <h5 class="modal-title" id="ProcedureModal-<%= procedure.id %>"><%= procedure.service.title %></h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                  <span aria-hidden="true">&times;</span>
                                </button>
                              </div>
                              <div class="modal-body">
                                <%= simple_format procedure.grievance %>
                              </div>
                              <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Fermer
                                </button>
                              </div>
                            </div>
                          </div>
                        </div>
                      </li>
                    </ul>
                  <% end %>
                <% end %>
              </div>
            <% end %>
			</div>
		</div>

    <div class="col-md-5">
      <div class="profile-block mb-4">
			<div class="card-product fixxed">
				<%= cl_image_tag @user.avatar, class:"lawyer-avatar"%>
				<div class="card-product-infos">
          <% if (@user.first_name.blank? && @user.last_name.blank?) %>
            <h6> <strong>Missing name</strong> 👉🏼 <%= link_to "Edit Profile", edit_user_registration_path %></h6>
          <% else  %>
					  <div class="d-flex justify-content-between">
              <h3 class="mr-4"><%= @user.first_name %> <%= @user.last_name %></h3>
              <p><%= link_to "Edit Profile", edit_user_registration_path %></p>
            </div>
          <% end %>
          <% if @jobs.present?  %>
					<p><%= @user.job %> chez <strong><%= @user.firm %></strong></p>
          <% end %>
					<div class="d-flex">
						<p><%= image_tag "location.svg", class:"location" %> <%= @user.address %></p>
					</div>
          <% if @user.specialty.nil? == false  %>
            <% @user.specialty.split(",").each do |special| %>
					    <a href="#" class="badge badge-primary"><%= special %></a>
            <% end %>
          <% end %>
				</div>
			</div>
		  </div>
      <div class="services-subblock">


      <% if @jobs.present?  %>
        <div class="card">
        <div class="card-header">Mes prestations :</div>
          <% @services.each do |service| %>
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              <div class="d-flex justify-content-between">
                <div>
                  <h6><%= service.title %></h6>
                  <p><small><%= service.category %></small></p>
                </div>
                <div>
                  <h6><%= service.duration %> semaines</h6>
                  <h6><%= service.price %>€</h6>
                </div>
              </div>
              <%= link_to 'Edit', edit_service_path(service) %>
              <%= link_to 'Destroy', service, method: :delete, data: { confirm: 'Êtes vous sur de vouloir supprimer cette prestation?' } %>
            </li>
          </ul>
          <% end %>
            <li class="list-group-item"><%= link_to 'Nouvelle prestation', new_service_path %>
            </li>
        </div>
      <% end %>


      </div>
    </div>
  </div>


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
		<title>Procédures Simplifiées</title>
		<%= csrf_meta_tags %> <%= action_cable_meta_tag %> <%= stylesheet_link_tag 'application', media: 'all' %> 
	</head>
	<body>
    <%= render 'shared/navbar' %>
		<div class="full-page">
			<%= yield %> 
		</div>
		<%= render 'shared/footer' %>
    <%= javascript_include_tag 'application' %> <%= javascript_pack_tag 'application' %>
	</body>
</html>

app/views/procedures/_form.html.erb
<div class="container col-md-6">
  <h3>Créer une procédure</h3>
  <%= simple_form_for [@service, @procedure] do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="form-inputs">
      <%= f.input :date, as: :date, html5: true %>
      <%= f.input :grievance, :label => "Quel est votre grief ?" %>
    </div>

    <div class="form-actions">
      <%= f.button :submit, class: "btn btn-primary"%>
    </div>
    <%= link_to 'Back', service_procedures_path(@service) %>
  <% end %>
</div>

app/views/procedures/index.html.erb
<div class="container">
<h2>Mes procédures</h2>
<% @procedures.each do |procedure| %>
  <ul><li>
  <h4><%= procedure.service.title %></h4>
  <p><%= procedure.status%></p>
  <p><%= procedure.grievance %></p>
  <p><%= procedure.date %></p>
  <p><%= procedure.user.last_name %></p>
  </li></ul>
<% end %>
  <%= link_to 'nouvelle procédure', new_service_procedure_path %>
</div>

app/views/procedures/new.html.erb
<div class="container">
  <div class="row">

    <div class="col-md-8">
      <h3>Créer une procédure de <%= @service.title %></h3>
      <%= simple_form_for [@service, @procedure] do |f| %>
        <%= f.error_notification %>
        <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

        <div class="form-inputs">
          <%= f.input :date, as: :date, html5: true %>
          <%= f.input :grievance, :label => "Quel est votre grief ?" %>
        </div>

        <div class="form-actions">
          <%= f.button :submit, class: "btn btn-primary"%>
        </div>
      <% end %>
    </div>


    <div class="col-4">
      <div class="recap">
        <div class="recap-header">
          <h3>Votre procédure</h3>
        </div>
        <ul class="bill">
          <h5><%= @service.title %></h5>
          <p>Un divorce rapide <strong class="float-right"><%= @service.price %> €</strong></p>
          <h4 class="total">TOTAL <strong class="float-right"><%= @service.price %> €</strong></h4>
        </ul>
        </div>
      </div>
    </div>


  </div>
</div>

app/views/procedures/show.html.erb
<div class="container">
  <p><%= @procedure.date %></p>
  <p><%= @procedure.grievance %></p>
  <p><%= @procedure.status %></p>
</div>

app/views/services/divorce.html.erb
<div class="container col-md-8">

  <h2>Avocats spécialisés en divorce </h2>

  <form class="form-inline mb-3 search-divorce">
    <input class="form-control" type="search" placeholder="Divorce">
    <button class="btn btn-primary" type="submit">Rechercher</button>
    <button type="button" class="btn btn-outline-secondary"><i class="fas fa-sliders-h"></i> Filtres</button>
  </form>

  <div class="card mb-3">

  <div class="card-haut d-flex justify-content-between">
    <div class="card-avatar-name d-flex">
      <img src="https://pbs.twimg.com/profile_images/564566896750493696/7LDNbQbV.jpeg" height="100" width="100" class="rounded-circle" alt="...">-->
      <p class="card-text pl-5"><span>Maître Saul Goodman</span> <br><small> Avocat à la Cour d'Albuquerque</small></p>
    </div>

    <div class="card-btn d-flex">
      <!-- <button type="button" class="btn btn-primary mr-3">Voir profil</button>
      <button type="button" class="btn btn-outline-primary mr-2">Prendre RDV</button> -->
      <%= link_to 'En savoir plus', profile_saul_path, class: "btn btn-primary mr-3" %>
      <%= link_to "Contacter l'avocat", new_service_procedure_path(@services.first), class: "btn btn-outline-primary mr-2" %>
    </div>
  </div>

  <div class="card-price-category-duration d-flex">
    <p class="card-text"><strong>Divorce</strong></p>
    <p class="card-text"><strong>Albuquerque, Nouveau Mexique</strong></p>
    <p class="card-text"><strong>4 semaines</strong></p>
    <p class="card-text"><strong>500 €</strong></p>
  </div>

  <div class="card-description">
    <p class="card-text">Don't want to go to jail ? Better call Saul !!</p>
  </div>

  <div class="card-tags">
    <a href="#" class="badge badge-primary">Droit pénal</a>
    <a href="#" class="badge badge-secondary">Droit de la famille</a>
    <a href="#" class="badge badge-light">Droit fiscal</a>
  </div>

</div>

<% @services.each do |service| %>

<div class="card mb-3">

  <div class="card-haut d-flex justify-content-between">
    <div class="card-avatar-name d-flex">
      <% unless @service.user.avatar.blank? %>
        <%= image_tag(service.user.avatar, class: "rounded-circle", width:"100px", height:"100px") %>
      <% end %>
      <p class="card-text pl-5">
        <span>Maître <%= service.user.first_name %> <%= service.user.last_name %></span>
        <br>
        <small> <%= service.user.job %> en <%= service.user.specialty %> </small>
        <br>
        📍<%= service.user.address %>
      </p>
    </div>

    <div class="card-btn d-flex">
      <%= link_to 'En savoir plus', service_path(service), class: "btn btn-primary mr-3" %>
      <%= link_to "Contacter l'avocat", new_service_procedure_path(service), class: "btn btn-outline-primary mr-2" %>
    </div>
  </div>
  <hr>
  <div class="card-price-category-duration d-flex">
    <p class="card-text"><strong>Procédure: </strong><%= service.title %></p>
    <p class="card-text"><strong>Durée: </strong><%= service.duration %> semaine(s)</p>
    <p class="card-text"><strong>Tarif: </strong><%= service.price %> € <small>TTC</small></p>
  </div>

  <div class="card-description">
    <p class="card-text"><strong>Description: </strong><%= service.description %></p>
  </div>

  <div class="card-tags">
    <a href="#" class="badge badge-primary">Droit pénal</a>
    <a href="#" class="badge badge-secondary">Droit de la famille</a>
    <a href="#" class="badge badge-light">Droit fiscal</a>
  </div>

</div>

  <% end %>
</div>

app/views/services/edit.html.erb
<div class="container col-6">
	<h1>Modifier votre prestation</h1>
	<%= render 'form', service: @service %> 
</div>

app/views/services/index.html.erb
<div class="container col-md-8">

  <!-- <h2> <%= @services.size %> résultat(s) disponible(s) </h2> -->

  <%if @services.size == 0 %>
    <h2>Aucun résultat disponible</h2>
    <%elsif @services.size == 1 %>
      <h2><%= @services.size %> résultat disponible</h2>
        <%else%>
          <h2><%= @services.size %> résultats disponibles</h2>
  <%end%>

  <!-- <form class="form-inline mb-3 search">
    <input class="form-control search-divorce" type="search" placeholder="Divorce">
    <button class="btn btn-primary" type="submit">Rechercher</button>
    <button type="button" class="btn btn-outline-secondary"><i class="fas fa-sliders-h"></i> Filtres</button>
  </form> -->

  <!-- Form de search query -->

  <%= form_tag services_path, class: "form-inline mb-3 search", method: :get do %>
    <%= text_field_tag :query,
      params[:query],
      class: "form-control search-divorce",
      placeholder: "Recherchez votre service..." %>
    <%= submit_tag "Rechercher", class: "submitbtn btn btn-primary" %>
    <button type="button" class="filterbtn btn btn-outline-secondary"><i class="fas fa-sliders-h"></i> Filtres</button>
  <% end %>

  <!-- Form de search query -->

<% @services.each do |service| %>

<div class="card mb-3">

  <div class="card-haut d-flex justify-content-between">
    <div class="card-avatar-name d-flex">
      <% if service.user.avatar.url.nil? == false %>
        <%= cl_image_tag(service.user.avatar, class: "rounded-circle", width:"100px", height:"100px") %>
      <% end %>
      <p class="card-text pl-5">
        <span>Maître <%= service.user.first_name %> <%= service.user.last_name %></span>
        <br>
        <small> <%= service.user.job %> en <%= service.user.specialty %> </small>
        <br>
        📍<%= service.user.address %>
      </p>
    </div>

    <div class="card-btn d-flex">
      <%= link_to 'En savoir plus', service_path(service), class: "btn btn-primary mr-3" %>
      <%= link_to "Contacter l'avocat", new_service_procedure_path(service), class: "btn btn-outline-primary mr-2" %>
    </div>
  </div>
  <hr>
  <div class="card-price-category-duration d-flex">
    <p class="card-text"><strong>Procédure: </strong><%= service.title %></p>
    <p class="card-text"><strong>Durée: </strong><%= service.duration %> semaine(s)</p>
    <p class="card-text"><strong>Tarif: </strong><%= service.price %> € <small>TTC</small></p>
  </div>

  <div class="card-description">
    <p class="card-text"><strong>Description: </strong><%= service.description %></p>
  </div>

  <div class="card-tags">
      <% if service.user.specialty %>
        <% service.user.specialty.split(",").each do |spe|  %>
          <a href="#" class="badge badge-primary"><%= spe %></a>
        <% end %>
      <% end %>
  </div>

</div>

<% end %>
</div>

app/views/services/new.html.erb
<div class="container col-4 pt-4">
  <h2>Créer une nouvelle prestation</h2>
    <%= render 'form', service: @service %>
</div>

app/views/services/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-8 p-5 section-1">
      <div class="row d-flex profile">
        <% if @service.user.avatar.url.nil? == false %>
          <%= cl_image_tag(@service.user.avatar)%>
        <% end %>
        <div class="pl-4">
          <small>Avocat à la cour</small>
          <h2><strong>Maître <%= @service.user.last_name %> </strong></h2>
          <p><strong>Spécialité: </strong><%= @service.category %></p>
          <p><strong>Votes: </strong>⭐️⭐️⭐️⭐️ (250 votes)</p>
          <p><strong>Durée procédure: </strong><%= @service.duration %> semaine(s)</p>
          <p><strong>Tarif (tout compris): </strong><%= @service.price %> €</p>
        </div>
      </div>
      <hr>
      <div class='section-2'>
        <h3>Détails la procédure</h3>
        <h5> <%= @service.description %> </h5>
        <br>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
        <br>
      </div>
    </div>
    <div class="col-4">
      <div class="recap">
        <div class="recap-header">
          <h5>La procédure comprend:</h5>
          <small><%= @service.title %></small>
        </div>
        <div class="list-group-recap">
          <p class="list-item">1. Vérification des conditions de recevabilité.</p>
          <p class="list-item">2. Emission du courrier de contestation.</p>
          <p class="list-item">3. Contestation automatisée.</p>
          <p class="list-item">4. Suivi de votre dossier auprès de la juridiction saisie.</p>
          <p class="list-item">5. Défense éventuelle de votre permis si convocation en justice.</p>
          <p class="list-item">6. Compte rendu de la décision obtenue et clôture du dossier.</p>
        </div>
        <%= link_to "Démarrer cette procédure", new_service_procedure_path(@service), class: "btn_1" %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% if @user.job == 'justiciable' %>
  <%= @user.first_name %>
  <%= @user.last_name %>
  <%= @user.email %>
  <% else %>
  <%= cl_image_tag @user.avatar, height: 300, width: 400, crop: :fill %>
  <%= @user.first_name %>
  <%= @user.last_name %>
  <%= @user.email %>
  <%= @user.job %>
  <%= @user.specialty %>
  <%= @user.address %>
  <%= @user.description %>
  <%= @user.experience %>
<% end %>

<% if current_user == @user %>
  <p><%= link_to 'Update my profile', edit_user_path(current_user), class: "btn btn-primary" %></p>

  <p><%= link_to 'Delete my profile', user_registration_path, data: { confirm: "Are you sure?" }, method: :delete, class: "btn btn-danger" %></p>
<% end %>



<!-- <p><%= link_to 'Delete my profile', user_registration_path(current_user), data: { confirm: "Are you sure?" }, method: :delete, class: "btn btn-danger" %></p> -->